export const templateJson = [
  {
    label: "vue3+ts+element-plus",
    value: "https://github.com/zyh-temp/react-temp.git",
    technical: "v",
    isTs: "1",
    url: "https://github.com/zyh-temp/react-temp.git",
  },
  {
    label: "vue3+ts+antdv",
    value: "https://github.com/zyh-temp/react-temp.git",
    technical: "v",
    isTs: "1",
    url: "https://github.com/zyh-temp/react-temp.git",
  },
  {
    label: "vue3+js+element-plus",
    value: "https://github.com/zyh-temp/react-temp.git",
    technical: "v",
    isTs: "0",
    url: "https://github.com/zyh-temp/react-temp.git",
  },
  {
    label: "vue3+js+antdv",
    value: "https://github.com/zyh-temp/react-temp.git",
    technical: "v",
    isTs: "0",
    url: "https://github.com/zyh-temp/react-temp.git",
  },
  {
    label: "react-ts-antd",
    value: "https://github.com/zyh-temp/react-temp.git",
    technical: "r",
    isTs: "1",
    url: "https://github.com/zyh-temp/react-temp.git",
  },
  {
    label: "react-js-antd",
    value: "https://github.com/zyh-temp/react-temp.git",
    technical: "r",
    isTs: "0",
    url: "https://github.com/zyh-temp/react-temp.git",
  },
  {
    label: "其他01-ts",
    value: "https://github.com/zyh-temp/react-temp.git",
    technical: "o",
    isTs: "1",
    url: "https://github.com/zyh-temp/react-temp.git",
  },
  {
    label: "其他02-ts",
    value: "https://github.com/zyh-temp/react-temp.git",
    technical: "o",
    isTs: "1",
    url: "https://github.com/zyh-temp/react-temp.git",
  },
  {
    label: "其他01-js",
    value: "https://github.com/zyh-temp/react-temp.git",
    technical: "o",
    isTs: "0",
    url: "https://github.com/zyh-temp/react-temp.git",
  },
  {
    label: "其他02-js",
    value: "https://github.com/zyh-temp/react-temp.git",
    technical: "o",
    isTs: "0",
    url: "https://github.com/zyh-temp/react-temp.git",
  },
];
